2024-05-14 06:44:28 ERROR 400 response executing GraphQL.
2024-05-14 06:44:28 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-05-14 06:44:28 ERROR Traceback (most recent call last):
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1055, in sweep
    response = self.gql(
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/cli/cli.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/cli/cli.py", line 1755, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/wandb_agent.py", line 570, in agent
    return run_agent(
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/wandb_agent.py", line 528, in run_agent
    agent.run()
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/wandb_agent.py", line 190, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/apis/internal.py", line 126, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: name required for project query (Error 400: Bad Request)

2024-05-14 06:46:21 ERROR 400 response executing GraphQL.
2024-05-14 06:46:21 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-05-14 06:46:21 ERROR Traceback (most recent call last):
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1055, in sweep
    response = self.gql(
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/cli/cli.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/cli/cli.py", line 1755, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/wandb_agent.py", line 570, in agent
    return run_agent(
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/wandb_agent.py", line 528, in run_agent
    agent.run()
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/wandb_agent.py", line 190, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/apis/internal.py", line 126, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/home/xjj/miniconda3/envs/python-3.8/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: name required for project query (Error 400: Bad Request)

2024-05-14 06:48:21 INFO Running runs: []
2024-05-14 06:48:21 INFO Agent received command: run
2024-05-14 06:48:21 INFO Agent starting run with config:
	batch_size: 80
	betas: (0.9
	eps: 1e-08
	lr: 0.004
	num_epochs: 10
	optimizer: adamax
	weight_decay: 0
2024-05-14 06:48:21 INFO About to run command: /usr/bin/env python df_wtf_pad/wtf_pad_close_world_train.py --batch_size=80 --betas=(0.9 --eps=1e-08 --lr=0.004 --num_epochs=10 --optimizer=adamax --weight_decay=0
2024-05-14 06:48:26 INFO Running runs: ['y1m1iphw']
2024-05-14 06:48:26 INFO Cleaning up finished run: y1m1iphw
2024-05-14 06:48:27 INFO Agent received command: run
2024-05-14 06:48:27 INFO Agent starting run with config:
	batch_size: 96
	betas: 0.999)
	eps: 1e-08
	lr: 0.007
	num_epochs: 20
	optimizer: adamax
	weight_decay: 0
2024-05-14 06:48:27 INFO About to run command: /usr/bin/env python df_wtf_pad/wtf_pad_close_world_train.py --batch_size=96 --betas=0.999) --eps=1e-08 --lr=0.007 --num_epochs=20 --optimizer=adamax --weight_decay=0
2024-05-14 06:49:30 INFO Running runs: []
2024-05-14 06:49:30 INFO Agent received command: run
2024-05-14 06:49:30 INFO Agent starting run with config:
	batch_size: 32
	betas: 0.999)
	eps: 1e-08
	lr: 0.004
	num_epochs: 20
	optimizer: sgd
	weight_decay: 0
2024-05-14 06:49:30 INFO About to run command: /usr/bin/env python df_wtf_pad/wtf_pad_close_world_train.py --batch_size=32 --betas=0.999) --eps=1e-08 --lr=0.004 --num_epochs=20 --optimizer=sgd --weight_decay=0
2024-05-14 06:49:35 INFO Running runs: ['1i3uac08']
2024-05-14 06:49:35 INFO Cleaning up finished run: 1i3uac08
2024-05-14 06:49:36 INFO Agent received command: run
2024-05-14 06:49:36 INFO Agent starting run with config:
	batch_size: 48
	betas: 0.999)
	eps: 1e-08
	lr: 0.005
	num_epochs: 50
	optimizer: adamax
	weight_decay: 0
2024-05-14 06:49:36 INFO About to run command: /usr/bin/env python df_wtf_pad/wtf_pad_close_world_train.py --batch_size=48 --betas=0.999) --eps=1e-08 --lr=0.005 --num_epochs=50 --optimizer=adamax --weight_decay=0
2024-05-14 06:49:59 INFO Running runs: []
2024-05-14 06:49:59 INFO Agent received command: run
2024-05-14 06:49:59 INFO Agent starting run with config:
	batch_size: 208
	betas: (0.9
	eps: 1e-08
	lr: 0.007
	num_epochs: 10
	optimizer: adamax
	weight_decay: 0
2024-05-14 06:49:59 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=208 --betas=(0.9 --eps=1e-08 --lr=0.007 --num_epochs=10 --optimizer=adamax --weight_decay=0
2024-05-14 06:50:04 INFO Running runs: ['8or7zr3x']
2024-05-14 06:53:25 INFO Running runs: []
2024-05-14 06:53:25 INFO Agent received command: run
2024-05-14 06:53:25 INFO Agent starting run with config:
	batch_size: 128
	betas: 0.999)
	eps: 1e-08
	lr: 0.009000000000000001
	num_epochs: 30
	optimizer: adam
	weight_decay: 0
2024-05-14 06:53:25 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=128 --betas=0.999) --eps=1e-08 --lr=0.009000000000000001 --num_epochs=30 --optimizer=adam --weight_decay=0
2024-05-14 06:53:30 INFO Running runs: ['kspp8v8h']
2024-05-14 06:55:21 INFO Running runs: []
2024-05-14 06:55:22 INFO Agent received command: run
2024-05-14 06:55:22 INFO Agent starting run with config:
	batch_size: 64
	betas: 0.999)
	eps: 1e-08
	lr: 0.004
	num_epochs: 10
	optimizer: adam
	weight_decay: 0
2024-05-14 06:55:22 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=64 --betas=0.999) --eps=1e-08 --lr=0.004 --num_epochs=10 --optimizer=adam --weight_decay=0
2024-05-14 06:55:27 INFO Running runs: ['2pgl3520']
2024-05-14 06:57:51 INFO Running runs: []
2024-05-14 06:57:51 INFO Agent received command: run
2024-05-14 06:57:51 INFO Agent starting run with config:
	batch_size: 128
	betas: 0.999)
	eps: 1e-08
	lr: 0.008
	num_epochs: 20
	optimizer: adamax
	weight_decay: 0
2024-05-14 06:57:51 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=128 --betas=0.999) --eps=1e-08 --lr=0.008 --num_epochs=20 --optimizer=adamax --weight_decay=0
2024-05-14 06:57:56 INFO Running runs: ['pr7j2ymj']
2024-05-14 06:58:12 INFO Cleaning up finished run: pr7j2ymj
2024-05-14 06:58:20 INFO Agent received command: run
2024-05-14 06:58:20 INFO Agent starting run with config:
	batch_size: 128
	betas: 0.999)
	eps: 1e-08
	lr: 0.005
	num_epochs: 10
	optimizer: adam
	weight_decay: 0
2024-05-14 06:58:20 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=128 --betas=0.999) --eps=1e-08 --lr=0.005 --num_epochs=10 --optimizer=adam --weight_decay=0
2024-05-14 06:58:25 INFO Running runs: ['k3d2ml05']
2024-05-14 06:58:46 INFO Cleaning up finished run: k3d2ml05
2024-05-14 06:58:46 INFO Agent received command: run
2024-05-14 06:58:46 INFO Agent starting run with config:
	batch_size: 80
	betas: 0.999)
	eps: 1e-08
	lr: 0.005
	num_epochs: 30
	optimizer: adam
	weight_decay: 0
2024-05-14 06:58:46 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=80 --betas=0.999) --eps=1e-08 --lr=0.005 --num_epochs=30 --optimizer=adam --weight_decay=0
2024-05-14 06:58:51 INFO Running runs: ['xjep02p3']
2024-05-14 06:59:13 INFO Cleaning up finished run: xjep02p3
2024-05-14 06:59:13 INFO Agent received command: run
2024-05-14 06:59:13 INFO Agent starting run with config:
	batch_size: 192
	betas: (0.9
	eps: 1e-08
	lr: 0.006
	num_epochs: 20
	optimizer: sgd
	weight_decay: 0
2024-05-14 06:59:13 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=192 --betas=(0.9 --eps=1e-08 --lr=0.006 --num_epochs=20 --optimizer=sgd --weight_decay=0
2024-05-14 06:59:18 INFO Running runs: ['7t5ih4j9']
2024-05-14 06:59:39 INFO Cleaning up finished run: 7t5ih4j9
2024-05-14 06:59:39 INFO Agent received command: run
2024-05-14 06:59:39 INFO Agent starting run with config:
	batch_size: 176
	betas: 0.999)
	eps: 1e-08
	lr: 0.005
	num_epochs: 10
	optimizer: adam
	weight_decay: 0
2024-05-14 06:59:39 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=176 --betas=0.999) --eps=1e-08 --lr=0.005 --num_epochs=10 --optimizer=adam --weight_decay=0
2024-05-14 06:59:44 INFO Running runs: ['1dxkw9nx']
2024-05-14 07:02:52 INFO Running runs: []
2024-05-14 07:02:52 INFO Agent received command: run
2024-05-14 07:02:52 INFO Agent starting run with config:
	batch_size: 208
	lr: 0.005
	num_epochs: 20
	optimizer: sgd
2024-05-14 07:02:52 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=208 --lr=0.005 --num_epochs=20 --optimizer=sgd
2024-05-14 07:02:57 INFO Running runs: ['rst8vsr1']
2024-05-14 07:03:07 INFO Cleaning up finished run: rst8vsr1
2024-05-14 07:03:14 INFO Agent received command: run
2024-05-14 07:03:14 INFO Agent starting run with config:
	batch_size: 16
	lr: 0.009000000000000001
	num_epochs: 10
	optimizer: sgd
2024-05-14 07:03:14 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=16 --lr=0.009000000000000001 --num_epochs=10 --optimizer=sgd
2024-05-14 07:03:19 INFO Running runs: ['204t3rpx']
2024-05-14 07:03:41 INFO Cleaning up finished run: 204t3rpx
2024-05-14 07:03:41 INFO Agent received command: run
2024-05-14 07:03:41 INFO Agent starting run with config:
	batch_size: 208
	lr: 0.009000000000000001
	num_epochs: 40
	optimizer: adam
2024-05-14 07:03:41 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=208 --lr=0.009000000000000001 --num_epochs=40 --optimizer=adam
2024-05-14 07:03:46 INFO Running runs: ['h4k1eg2n']
2024-05-14 07:04:07 INFO Cleaning up finished run: h4k1eg2n
2024-05-14 07:04:07 INFO Agent received command: run
2024-05-14 07:04:07 INFO Agent starting run with config:
	batch_size: 160
	lr: 0.008
	num_epochs: 10
	optimizer: adam
2024-05-14 07:04:07 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=160 --lr=0.008 --num_epochs=10 --optimizer=adam
2024-05-14 07:04:12 INFO Running runs: ['7xzg08bi']
2024-05-14 07:04:34 INFO Cleaning up finished run: 7xzg08bi
2024-05-14 07:04:34 INFO Agent received command: run
2024-05-14 07:04:34 INFO Agent starting run with config:
	batch_size: 112
	lr: 0.003
	num_epochs: 20
	optimizer: sgd
2024-05-14 07:04:34 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=112 --lr=0.003 --num_epochs=20 --optimizer=sgd
2024-05-14 07:04:39 INFO Running runs: ['closxolg']
2024-05-14 07:05:00 ERROR Detected 5 failed runs in a row, shutting down.
2024-05-14 07:05:00 INFO To change this value set WANDB_AGENT_MAX_INITIAL_FAILURES=val
2024-05-14 07:08:32 INFO Running runs: []
2024-05-14 07:08:32 INFO Agent received command: run
2024-05-14 07:08:32 INFO Agent starting run with config:
	batch_size: 80
	lr: 0.005
	num_epochs: 40
	optimizer: adamax
2024-05-14 07:08:32 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=80 --lr=0.005 --num_epochs=40 --optimizer=adamax
2024-05-14 07:08:37 INFO Running runs: ['n5r4i9a2']
2024-05-14 07:08:53 INFO Cleaning up finished run: n5r4i9a2
2024-05-14 07:10:48 INFO Running runs: []
2024-05-14 07:10:49 INFO Agent received command: run
2024-05-14 07:10:49 INFO Agent starting run with config:
	batch_size: 240
	lr: 0.006
	num_epochs: 50
	optimizer: sgd
2024-05-14 07:10:49 INFO About to run command: /usr/bin/env python wtf_pad_close_world_train.py --batch_size=240 --lr=0.006 --num_epochs=50 --optimizer=sgd
2024-05-14 07:10:54 INFO Running runs: ['9k15baq4']
2024-05-14 07:30:28 INFO Cleaning up finished run: 9k15baq4
2024-05-14 07:32:40 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')': /api/4504800232407040/envelope/
